# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
</style> 


<p id="dota" style="background-color: silver; color: white;">
   Do you know the game Dota2?</p>
<input type="radio" name="dota_1" value="Yes">Yes</input>
<input type="radio" name="dota_2" value="No">No</input>

<div id="result"></div>
<p id="dota" style="background-color: silver; color: white;">
   This is a random pool of Dota2 abilities. Please select one ability below to see its win rate:</p>
   
<input type="radio" name="ability" value="Yes" id="A"> slark shadow dance</input><br>
<input type="radio" name="ability" value="Yes" id="C"> disruptor thunder strike</input><br>
<input type="radio" name="ability" value="Yes" id="F"> necrolyte reapers scythe</input><br>
<input type="radio" name="ability" value="Yes" id="G"> phoenix icarus dive</input><br>
<input type="radio" name="ability" value="Yes" id="H"> sniper assassinate</input><br>
<input type="radio" name="ability" value="Yes" id="D"> earthshaker aftershock</input><br>
<input type="radio" name="ability" value="Yes" id="E"> windrunner windrun</input><br>
<input type="radio" name="ability" value="Yes" id="I"> omniknight martyr</input><br>
<input type="radio" name="ability" value="Yes" id="J"> tidehunter anchor smash</input><br>
<input type="radio" name="ability" value="Yes" id="B"> beastmaster wild axes</input><br>

<div id="plot"></div>
<p></p>

<p id="dota" style="background-color: silver; color: white;">
   This is a random pool of Dota2 heroes. Please select one hero below to see its win rate:</p>

<input type="radio" name="hero" value="Yes" id="1"> Mars</input><br>
<input type="radio" name="hero" value="Yes" id="3"> Elder Titan</input><br>
<input type="radio" name="hero" value="Yes" id="5"> Batrider</input><br>
<input type="radio" name="hero" value="Yes" id="7"> Slark</input><br>
<input type="radio" name="hero" value="Yes" id="4"> Lone Druid</input><br>
<input type="radio" name="hero" value="Yes" id="8"> Zeus</input><br>
<input type="radio" name="hero" value="Yes" id="9"> Broodmother</input><br>
<input type="radio" name="hero" value="Yes" id="6"> Phantom Assassin</input><br>
<input type="radio" name="hero" value="Yes" id="10"> Undying</input><br>
<input type="radio" name="hero" value="Yes" id="2"> Bane</input><br>

<div id="plot_2"></div>
<p></p>

<p id="dota" style="background-color: silver; color: white;">
   Now look at the important attributes for each ability:</p>

<input type="radio" name="ability" value="Yes" id="Q"> slark shadow dance</input><br>
<input type="radio" name="ability" value="Yes" id="R"> disruptor thunder strike</input><br>
<input type="radio" name="ability" value="Yes" id="S"> necrolyte reapers scythe</input><br>
<input type="radio" name="ability" value="Yes" id="T"> phoenix icarus dive</input><br>
<input type="radio" name="ability" value="Yes" id="U"> sniper assassinate</input><br>
<input type="radio" name="ability" value="Yes" id="V"> earthshaker aftershock</input><br>
<input type="radio" name="ability" value="Yes" id="W"> windrunner windrun</input><br>
<input type="radio" name="ability" value="Yes" id="X"> omniknight martyr</input><br>
<input type="radio" name="ability" value="Yes" id="Y"> tidehunter anchor smash</input><br>
<input type="radio" name="ability" value="Yes" id="Z"> beastmaster wild axes</input><br>

<div id="plot_3"></div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>


